root: true
env:
  commonjs: true
  browser: true
  es2021: true
  mocha: true
  node: true
parserOptions:
  ecmaVersion: 12
  sourceType: module
extends:
  - airbnb-base
  - prettier
plugins:
  - import
globals:
  expect: readonly
  supertest: readonly
ignorePatterns:
  - '/*'
  - '!src/'
  - '!tests/'
rules:
  camelcase: 0
  no-unused-vars:
    #! example - if not using 'req': router.get((_req, res, next) => {})
    - error
    - argsIgnorePattern: ^_
  linebreak-style:
    - error
    - unix
  no-empty-function:
    - error
    - allow:
        - methods
  no-plusplus: 0
  no-return-assign: 0
  no-param-reassign: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
