parserOptions:
  ecmaVersion: 11
env:
  browser: true
  commonjs: true
  es2020: true
# Use this for 3rd-party linter libraries
extends:
  - 'eslint:recommended'
  # - eslint-config-airbnb
  # - airbnb
  # - airbnb/hooks
rules:
  prefer-stateless-function: off
  linebreak-style: 0
  import/extensions: off
  comma-dangle: 0
  no-trailing-spaces: 0
# plugins:
#   - import
settings:
  import/parser: babel-eslint
  import/resolve:
    moduleDirectory:
      - node_modules
      - src
